[package]
name = "local_backend"
version = "0.1.0"
edition = "2021"
license = "LicenseRef-FSL-1.1-Apache-2.0"

[[bin]]
name = "convex-local-backend"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
application = { path = "../application" }
async-broadcast = { workspace = true }
async-trait = { workspace = true }
authentication = { path = "../authentication" }
axum = { workspace = true }
axum-extra = { workspace = true }
base64 = { workspace = true }
clap = { workspace = true }
clusters = { path = "../clusters" }
cmd_util = { path = "../cmd_util" }
common = { path = "../common" }
convex_fivetran_destination = { path = "../fivetran_destination" }
database = { path = "../database" }
either = { workspace = true }
errors = { path = "../errors" }
events = { path = "../events" }
fastrace = { workspace = true }
file_storage = { path = "../file_storage" }
function_runner = { path = "../function_runner" }
futures = { workspace = true }
futures-async-stream = { workspace = true }
http = { workspace = true }
http-body-util = { workspace = true }
hyper-util = { workspace = true }
isolate = { path = "../isolate" }
keybroker = { path = "../keybroker" }
maplit = { workspace = true }
metrics = { path = "../metrics" }
model = { path = "../model" }
mysql = { path = "../mysql" }
node_executor = { path = "../node_executor" }
parking_lot = { workspace = true }
postgres = { path = "../postgres" }
rand = { workspace = true }
reqwest = { workspace = true }
runtime = { path = "../runtime" }
search = { path = "../search" }
sentry = { workspace = true }
sentry-tracing = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sodiumoxide = { workspace = true }
sqlite = { path = "../sqlite" }
storage = { path = "../storage" }
sync = { path = "../sync" }
sync_types = { package = "convex_sync_types", path = "../convex/sync_types" }
tempfile = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tower = { workspace = true }
tower-http = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
tungstenite = { workspace = true }
udf = { path = "../udf" }
url = { workspace = true }
urlencoding = { workspace = true }
usage_tracking = { path = "../usage_tracking" }
value = { path = "../value" }
vector = { path = "../vector" }

[dev-dependencies]
application = { path = "../application", features = ["testing"] }
authentication = { path = "../authentication", features = ["testing"] }
common = { path = "../common", features = ["testing"] }
convex_macro = { path = "../convex_macro" }
database = { path = "../database", features = ["testing"] }
errors = { path = "../errors", features = ["testing"] }
events = { path = "../events", features = ["testing"] }
function_runner = { path = "../function_runner", features = ["testing"] }
isolate = { path = "../isolate", features = ["testing"] }
keybroker = { path = "../keybroker", features = ["testing"] }
metrics = { path = "../metrics", features = ["testing"] }
model = { path = "../model", features = ["testing"] }
mysql = { path = "../mysql", features = ["testing"] }
node_executor = { path = "../node_executor", features = ["testing"] }
portpicker = { workspace = true }
postgres = { path = "../postgres", features = ["testing"] }
runtime = { path = "../runtime", features = ["testing"] }
search = { path = "../search", features = ["testing"] }
storage = { path = "../storage", features = ["testing"] }
sync = { path = "../sync", features = ["testing"] }
tokio-tungstenite = { workspace = true }
udf = { path = "../udf", features = ["testing"] }
usage_tracking = { path = "../usage_tracking", features = ["testing"] }
value = { path = "../value", features = ["testing"] }
vector = { path = "../vector", features = ["testing"] }

[build-dependencies]
anyhow = { workspace = true }
vergen = { workspace = true, features = ["git", "gitcl"] }

[lints]
workspace = true
